### ISSUE TITLE
[No Support For C++14 and above template functions]

### ISSUE THREAD

**Issue by jishnupramod** [williammu6/vscode-input#1]
The C++ template structures and functions included in C++14 are not getting compiled using the build command (Command+Shift+B).
`
unordered_map<int, int> mp;
`
`error: no template named 'unordered_map'
    unordered_map<int, int> mp;
    ^
1 error generated.
`

**Comment by williammu6** [comment]
Hey, thanks for reporting the issue!

Have you tried to add the -std flag to the compilation command?
If you haven't, then you can modify the command used to compile your code by opening VSCode Preferences and changing the compilation command such as the example:

**"vscode-input.compile-command.cpp": "g++ -lm -std=c++11 $path -o $output"**.

**Comment by jishnupramod** [comment]
Changing the compile command to support C++11 worked! Thanks :)
